"""need vector index added

Revision ID: 0b28c4605cd3
Revises: 34329c836370
Create Date: 2026-07-07 11:02:44.723499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b28c4605cd3'
down_revision = '34329c836370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_embeddings', schema=None) as batch_op:
        batch_op.create_index('embedding_vector_idx', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_embeddings', schema=None) as batch_op:
        batch_op.drop_index('embedding_vector_idx', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})

    # ### end Alembic commands ###
