"""update contract table

Revision ID: 4fb50e82576e
Revises: 544cfabca747
Create Date: 2026-07-06 16:06:36.508219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb50e82576e'
down_revision = '544cfabca747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_created', sa.Boolean(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_chunks_contract_id'), ['contract_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_value_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('solicitation_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('psc_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('chunk_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('embedding_version', sa.Integer(), nullable=True))
        batch_op.drop_column('semantic_score')
        batch_op.drop_column('embedding_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_created', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semantic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('embedding_version')
        batch_op.drop_column('chunk_count')
        batch_op.drop_column('psc_code')
        batch_op.drop_column('solicitation_number')
        batch_op.drop_column('estimated_value_text')

    with op.batch_alter_table('contract_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_chunks_contract_id'))

    op.drop_table('contract_chunks')
    # ### end Alembic commands ###
