"""update contracts table

Revision ID: 544cfabca747
Revises: f43918dbf4b9
Create Date: 2026-07-06 15:47:17.944222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544cfabca747'
down_revision = 'f43918dbf4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('office', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notice_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('set_aside', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estimated_value', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('response_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('embedding_created', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('biddability_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('proposal_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proposal_submitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('sam_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('sam_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('proposal_submitted')
        batch_op.drop_column('proposal_generated')
        batch_op.drop_column('biddability_tier')
        batch_op.drop_column('embedding_model')
        batch_op.drop_column('embedding_created')
        batch_op.drop_column('response_deadline')
        batch_op.drop_column('estimated_value')
        batch_op.drop_column('status')
        batch_op.drop_column('set_aside')
        batch_op.drop_column('notice_type')
        batch_op.drop_column('office')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
