"""update contract table

Revision ID: 60bec2772e47
Revises: 4fb50e82576e
Create Date: 2026-07-06 16:58:19.301175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bec2772e47'
down_revision = '4fb50e82576e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_status', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('embedded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('embedding_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('embedding_error')
        batch_op.drop_column('embedded_at')
        batch_op.drop_column('embedding_status')

    # ### end Alembic commands ###
